"""
Findings Reporter Agent

Saves findings to SQLite and sends notifications to Telegram.
"""

import json
import sqlite3
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent.parent.parent / "data" / "research.db"

def save_pump_to_db(pump: dict) -> int:
    """Save a detected pump to database and return its ID."""
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("""
            INSERT INTO pumps (symbol, price_change_pct, time_window_minutes,
                             price_at_detection, volume_change_pct, market_cap, source)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            pump["symbol"],
            pump["price_change_pct"],
            pump.get("time_window_minutes", 60),
            pump.get("price_at_detection"),
            pump.get("volume_change_pct"),
            pump.get("market_cap"),
            pump.get("source", "unknown")
        ))
        return cursor.lastrowid

def save_findings_to_db(pump_id: int, findings: list[dict]) -> list[int]:
    """Save investigation findings to database."""
    finding_ids = []
    with sqlite3.connect(DB_PATH) as conn:
        for finding in findings:
            cursor = conn.execute("""
                INSERT INTO findings (pump_id, source_type, source_url, content,
                                    relevance_score, sentiment, metadata)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                pump_id,
                finding.get("source_type"),
                finding.get("source_url"),
                finding.get("content"),
                finding.get("relevance_score"),
                finding.get("sentiment"),
                json.dumps(finding.get("metadata", {}))
            ))
            finding_ids.append(cursor.lastrowid)
    return finding_ids

def save_trigger_to_db(pump_id: int, trigger: dict, finding_ids: list[int]) -> int:
    """Save identified news trigger to database."""
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("""
            INSERT INTO news_triggers (pump_id, trigger_type, description,
                                      confidence, supporting_findings)
            VALUES (?, ?, ?, ?, ?)
        """, (
            pump_id,
            trigger.get("trigger_type", "unknown"),
            trigger.get("description", ""),
            trigger.get("confidence", 0.0),
            json.dumps(finding_ids)
        ))
        return cursor.lastrowid

def get_telegram_report_prompt(pump: dict, investigation: dict) -> str:
    """Generate prompt to send Telegram notification."""
    findings_summary = ""
    for f in investigation.get("findings", [])[:3]:  # Top 3 findings
        findings_summary += f"\n- [{f.get('source_type', 'unknown').upper()}] {f.get('content', '')[:100]}"

    trigger = investigation.get("likely_trigger", {})
    trigger_type = trigger.get('trigger_type', 'Unknown').replace('_', ' ').title()

    return f"""
Use the Telegram MCP to send this research finding to the configured chat.

## Message to Send

🚀 **PUMP DETECTED: ${pump['symbol']}**

📈 **Price Change:** +{pump['price_change_pct']:.1f}% (1h)
💰 **Price:** ${pump.get('price_at_detection', 'N/A')}
📊 **Volume Change:** {pump.get('volume_change_pct', 'N/A')}%

🔍 **Likely Trigger:** {trigger_type}
📝 {trigger.get('description', 'No description available')}
🎯 **Confidence:** {trigger.get('confidence', 0) * 100:.0f}%

**Key Findings:**{findings_summary if findings_summary else '\n- No specific findings identified'}

**Summary:**
{investigation.get('summary', 'No summary available')}

---
_Generated by Pump Researcher Agent_
_Detected at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_

---

Send this message to the chat ID configured in TELEGRAM_CHAT_ID environment variable.
Return the message ID after sending.
"""

def save_notification_to_db(pump_id: int, chat_id: str, message_id: str = None, status: str = "sent"):
    """Record that a notification was sent."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            INSERT INTO notifications (pump_id, chat_id, message_id, status)
            VALUES (?, ?, ?, ?)
        """, (pump_id, chat_id, message_id, status))

def start_agent_run() -> int:
    """Record the start of an agent run."""
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("""
            INSERT INTO agent_runs (status) VALUES ('running')
        """)
        return cursor.lastrowid

def complete_agent_run(run_id: int, pumps_detected: int, findings_count: int,
                       status: str = "completed", error: str = None):
    """Record the completion of an agent run."""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            UPDATE agent_runs
            SET completed_at = CURRENT_TIMESTAMP,
                pumps_detected = ?,
                findings_count = ?,
                status = ?,
                error_message = ?
            WHERE id = ?
        """, (pumps_detected, findings_count, status, error, run_id))
